spring:
  #静态资源处理
  web:
    resources:
      #启动默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存相应时间，单位秒
          max-age: 3600
      chain:
        #资源链启动缓存，默认启动
        cache: true
        #启动资源链，默认禁用
        enabled: true
        #启用压缩资源（gzip，brotli）解析，默认禁用
        compressed: true
      static-locations: classpath:/static/

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.64.223:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 314159
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 这个属性控制连接池中空闲连接的最大空闲时间，只有当连接池中连接数量大于最小连接数量(minimumIdle)时会生效，默认10分钟
      idle-timeout: 1800000
      # 从连接池中返回的连接是否自动提交事务
      auto-commit: true
      # 这个属性控制连接池中一个连接的最大生存时间，当一个连接的生存时间大于这个值且没有正在被使用时，将会被关掉
      # 不管当前连接数是否大于最小连接数量，默认30分钟
      max-lifetime: 1800000
      # 连接超时时间，默认30秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 120.78.64.223
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 8
        min-idle: 5
  rabbitmq:
    #服务器地址
    host: 120.78.64.223
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量，即@RabbitListener开启几个线程去处理数据
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false（发送信息到队列中失败时，是否重试）
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000
        #重试最大次数
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000
        #重试间隔的乘数，比如设置为2，第一次等10s，第二次等20s，第三次等40s
        multiplier: 1


mybatis-plus:
  # 配置mapper.xml映射的位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.example.seckill.pojo

# Mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.example.seckill.mapper: debug
